services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fibertime-net

  fibertime-fe:
    build:
      context: ./fibertime_fe
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./fibertime_fe:/app
      - ./fibertime_fe/package-lock.json:/app/package-lock.json
      - fe-next:/app/.next
      - fe-modules:/app/node_modules
    networks:
      - fibertime-net
    env_file:
      - ./.env

  fibertime-be:
    build:
      context: ./fibertime_be
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./fibertime_be:/app
      - be-modules:/app/node_modules
    depends_on:
      - fibertime-db
    networks:
      - fibertime-net
    env_file:
      - ./.env

  fibertime-db:
    image: postgres:16
    restart: always
    ports:
      - ${BE_DB_PORT}:${BE_DB_PORT}
    environment:
      - POSTGRES_USER=${BE_DB_USER}
      - POSTGRES_PASSWORD=${BE_DB_PASS}
      - POSTGRES_DB=${BE_DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - fibertime-db:/var/lib/postgresql/data/pgdata
    networks:
      - fibertime-net

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - fibertime-net

networks:
  fibertime-net:

volumes:
  fibertime-db:
  fe-modules:
  fe-next:
  be-modules:
  redis-data:
